name: Spark Processing
run-name: Process dataset with spark
on:
  workflow_dispatch:
  repository_dispatch:
    types: [Spark-Processing]
jobs:
  Spark-Processing:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: "3.5.5"
      - name: Process dataset using spark
        run: |
          ls -l -R
          rm results/data.json
          spark-submit --master local spark_processor_src/spark_processor.py
          ls -l -R
      - name: Commit dataset to repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add results/
          git commit -m "Refresh spark results"
          git push
